version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced go vet
    - unused        # Check for unused constants, variables, functions and types
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible, flexible linter
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gosec         # Security checks
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocyclo       # Computes and checks cyclomatic complexity
    - bodyclose     # Checks whether HTTP response body is closed successfully
